docker_image(
    name="docker",
    repository="darkform/tornatura.bollettini",
    image_tags=["latest", "2.1.0"],
    dependencies=[
        "src/python/bollettini:scheduler",
        "src/python/bollettini:api"
    ],
)
