docker_image(
    name="docker",
    repository="darkform/tornatura.landscape",
    image_tags=["latest", "2.2.0"],
    dependencies=[
        "src/python/landscape:api",
        "src/python/landscape:updater",
    ],
)
