docker_image(
    name="docker",
    repository="darkform/tornatura.web",
    image_tags=["0.2.202603231300", "latest"],
    dependencies=["src/typescript/web:artifacts", "src/typescript/libs:artifacts"]
)
