/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AgriField } from '../models';
import { AgriFieldMutationPayload } from '../models';
import { ErrorResponse } from '../models';
import { PaginatedResponse } from '../models';
/**
 * AgriFieldsApi - axios parameter creator
 * @export
 */
export const AgriFieldsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Agriculture Field
         * @param {AgriFieldMutationPayload} body 
         * @param {string} orgId Organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAgrifield: async (body: AgriFieldMutationPayload, orgId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createAgrifield.');
            }
            // verify required parameter 'orgId' is not null or undefined
            if (orgId === null || orgId === undefined) {
                throw new RequiredError('orgId','Required parameter orgId was null or undefined when calling createAgrifield.');
            }
            const localVarPath = `/v1/organizations/{org_id}/agrifields`
                .replace(`{${"org_id"}}`, encodeURIComponent(String(orgId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create Agriculture Field
         * @param {AgriFieldMutationPayload} body 
         * @param {string} orgId Organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAgrifield_1: async (body: AgriFieldMutationPayload, orgId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createAgrifield_1.');
            }
            // verify required parameter 'orgId' is not null or undefined
            if (orgId === null || orgId === undefined) {
                throw new RequiredError('orgId','Required parameter orgId was null or undefined when calling createAgrifield_1.');
            }
            const localVarPath = `/v1/organizations/{org_id}/agrifields`
                .replace(`{${"org_id"}}`, encodeURIComponent(String(orgId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Agriculture Field details
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agrifield ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAgrifield: async (orgId: string, agrifieldId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgId' is not null or undefined
            if (orgId === null || orgId === undefined) {
                throw new RequiredError('orgId','Required parameter orgId was null or undefined when calling getAgrifield.');
            }
            // verify required parameter 'agrifieldId' is not null or undefined
            if (agrifieldId === null || agrifieldId === undefined) {
                throw new RequiredError('agrifieldId','Required parameter agrifieldId was null or undefined when calling getAgrifield.');
            }
            const localVarPath = `/v1/organizations/{org_id}/agrifields/{agrifield_id}`
                .replace(`{${"org_id"}}`, encodeURIComponent(String(orgId)))
                .replace(`{${"agrifield_id"}}`, encodeURIComponent(String(agrifieldId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Agriculture Field details
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agrifield ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAgrifield_2: async (orgId: string, agrifieldId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgId' is not null or undefined
            if (orgId === null || orgId === undefined) {
                throw new RequiredError('orgId','Required parameter orgId was null or undefined when calling getAgrifield_2.');
            }
            // verify required parameter 'agrifieldId' is not null or undefined
            if (agrifieldId === null || agrifieldId === undefined) {
                throw new RequiredError('agrifieldId','Required parameter agrifieldId was null or undefined when calling getAgrifield_2.');
            }
            const localVarPath = `/v1/organizations/{org_id}/agrifields/{agrifield_id}`
                .replace(`{${"org_id"}}`, encodeURIComponent(String(orgId)))
                .replace(`{${"agrifield_id"}}`, encodeURIComponent(String(agrifieldId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Agriculture Fields
         * @param {string} orgId Organization ID
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAgrifields: async (orgId: string, page?: number, limit?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgId' is not null or undefined
            if (orgId === null || orgId === undefined) {
                throw new RequiredError('orgId','Required parameter orgId was null or undefined when calling listAgrifields.');
            }
            const localVarPath = `/v1/organizations/{org_id}/agrifields`
                .replace(`{${"org_id"}}`, encodeURIComponent(String(orgId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Agriculture Fields
         * @param {string} orgId Organization ID
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAgrifields_3: async (orgId: string, page?: number, limit?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgId' is not null or undefined
            if (orgId === null || orgId === undefined) {
                throw new RequiredError('orgId','Required parameter orgId was null or undefined when calling listAgrifields_3.');
            }
            const localVarPath = `/v1/organizations/{org_id}/agrifields`
                .replace(`{${"org_id"}}`, encodeURIComponent(String(orgId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AgriFieldsApi - functional programming interface
 * @export
 */
export const AgriFieldsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Agriculture Field
         * @param {AgriFieldMutationPayload} body 
         * @param {string} orgId Organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAgrifield(body: AgriFieldMutationPayload, orgId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AgriField>>> {
            const localVarAxiosArgs = await AgriFieldsApiAxiosParamCreator(configuration).createAgrifield(body, orgId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Create Agriculture Field
         * @param {AgriFieldMutationPayload} body 
         * @param {string} orgId Organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAgrifield_1(body: AgriFieldMutationPayload, orgId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AgriField>>> {
            const localVarAxiosArgs = await AgriFieldsApiAxiosParamCreator(configuration).createAgrifield_1(body, orgId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get Agriculture Field details
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agrifield ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAgrifield(orgId: string, agrifieldId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AgriField>>> {
            const localVarAxiosArgs = await AgriFieldsApiAxiosParamCreator(configuration).getAgrifield(orgId, agrifieldId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get Agriculture Field details
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agrifield ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAgrifield_2(orgId: string, agrifieldId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AgriField>>> {
            const localVarAxiosArgs = await AgriFieldsApiAxiosParamCreator(configuration).getAgrifield_2(orgId, agrifieldId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary List Agriculture Fields
         * @param {string} orgId Organization ID
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listAgrifields(orgId: string, page?: number, limit?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PaginatedResponse>>> {
            const localVarAxiosArgs = await AgriFieldsApiAxiosParamCreator(configuration).listAgrifields(orgId, page, limit, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary List Agriculture Fields
         * @param {string} orgId Organization ID
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listAgrifields_3(orgId: string, page?: number, limit?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PaginatedResponse>>> {
            const localVarAxiosArgs = await AgriFieldsApiAxiosParamCreator(configuration).listAgrifields_3(orgId, page, limit, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AgriFieldsApi - factory interface
 * @export
 */
export const AgriFieldsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Create Agriculture Field
         * @param {AgriFieldMutationPayload} body 
         * @param {string} orgId Organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAgrifield(body: AgriFieldMutationPayload, orgId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<AgriField>> {
            return AgriFieldsApiFp(configuration).createAgrifield(body, orgId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create Agriculture Field
         * @param {AgriFieldMutationPayload} body 
         * @param {string} orgId Organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAgrifield_1(body: AgriFieldMutationPayload, orgId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<AgriField>> {
            return AgriFieldsApiFp(configuration).createAgrifield_1(body, orgId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Agriculture Field details
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agrifield ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAgrifield(orgId: string, agrifieldId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<AgriField>> {
            return AgriFieldsApiFp(configuration).getAgrifield(orgId, agrifieldId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Agriculture Field details
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agrifield ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAgrifield_2(orgId: string, agrifieldId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<AgriField>> {
            return AgriFieldsApiFp(configuration).getAgrifield_2(orgId, agrifieldId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Agriculture Fields
         * @param {string} orgId Organization ID
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listAgrifields(orgId: string, page?: number, limit?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<PaginatedResponse>> {
            return AgriFieldsApiFp(configuration).listAgrifields(orgId, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Agriculture Fields
         * @param {string} orgId Organization ID
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listAgrifields_3(orgId: string, page?: number, limit?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<PaginatedResponse>> {
            return AgriFieldsApiFp(configuration).listAgrifields_3(orgId, page, limit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AgriFieldsApi - object-oriented interface
 * @export
 * @class AgriFieldsApi
 * @extends {BaseAPI}
 */
export class AgriFieldsApi extends BaseAPI {
    /**
     * 
     * @summary Create Agriculture Field
     * @param {AgriFieldMutationPayload} body 
     * @param {string} orgId Organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AgriFieldsApi
     */
    public async createAgrifield(body: AgriFieldMutationPayload, orgId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<AgriField>> {
        return AgriFieldsApiFp(this.configuration).createAgrifield(body, orgId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Create Agriculture Field
     * @param {AgriFieldMutationPayload} body 
     * @param {string} orgId Organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AgriFieldsApi
     */
    public async createAgrifield_1(body: AgriFieldMutationPayload, orgId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<AgriField>> {
        return AgriFieldsApiFp(this.configuration).createAgrifield_1(body, orgId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get Agriculture Field details
     * @param {string} orgId Organization ID
     * @param {string} agrifieldId Agrifield ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AgriFieldsApi
     */
    public async getAgrifield(orgId: string, agrifieldId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<AgriField>> {
        return AgriFieldsApiFp(this.configuration).getAgrifield(orgId, agrifieldId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get Agriculture Field details
     * @param {string} orgId Organization ID
     * @param {string} agrifieldId Agrifield ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AgriFieldsApi
     */
    public async getAgrifield_2(orgId: string, agrifieldId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<AgriField>> {
        return AgriFieldsApiFp(this.configuration).getAgrifield_2(orgId, agrifieldId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary List Agriculture Fields
     * @param {string} orgId Organization ID
     * @param {number} [page] Page number
     * @param {number} [limit] Items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AgriFieldsApi
     */
    public async listAgrifields(orgId: string, page?: number, limit?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<PaginatedResponse>> {
        return AgriFieldsApiFp(this.configuration).listAgrifields(orgId, page, limit, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary List Agriculture Fields
     * @param {string} orgId Organization ID
     * @param {number} [page] Page number
     * @param {number} [limit] Items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AgriFieldsApi
     */
    public async listAgrifields_3(orgId: string, page?: number, limit?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<PaginatedResponse>> {
        return AgriFieldsApiFp(this.configuration).listAgrifields_3(orgId, page, limit, options).then((request) => request(this.axios, this.basePath));
    }
}
