/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { DetectionType } from '../models';
import { DetectionTypeCreatePayload } from '../models';
import { DetectionTypeUpdatePayload } from '../models';
import { ErrorResponse } from '../models';
import { PaginatedResponse } from '../models';
import { StatusResponse } from '../models';
/**
 * DetectionTypesApi - axios parameter creator
 * @export
 */
export const DetectionTypesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Detection Type
         * @param {DetectionTypeCreatePayload} body 
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agriculture Field ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDetectionType: async (body: DetectionTypeCreatePayload, orgId: string, agrifieldId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createDetectionType.');
            }
            // verify required parameter 'orgId' is not null or undefined
            if (orgId === null || orgId === undefined) {
                throw new RequiredError('orgId','Required parameter orgId was null or undefined when calling createDetectionType.');
            }
            // verify required parameter 'agrifieldId' is not null or undefined
            if (agrifieldId === null || agrifieldId === undefined) {
                throw new RequiredError('agrifieldId','Required parameter agrifieldId was null or undefined when calling createDetectionType.');
            }
            const localVarPath = `/v1/organizations/{org_id}/agrifields/{agrifield_id}/detection-types`
                .replace(`{${"org_id"}}`, encodeURIComponent(String(orgId)))
                .replace(`{${"agrifield_id"}}`, encodeURIComponent(String(agrifieldId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Detection Type
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agriculture Field ID
         * @param {string} detectionTypeId Detection Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDetectionType: async (orgId: string, agrifieldId: string, detectionTypeId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgId' is not null or undefined
            if (orgId === null || orgId === undefined) {
                throw new RequiredError('orgId','Required parameter orgId was null or undefined when calling deleteDetectionType.');
            }
            // verify required parameter 'agrifieldId' is not null or undefined
            if (agrifieldId === null || agrifieldId === undefined) {
                throw new RequiredError('agrifieldId','Required parameter agrifieldId was null or undefined when calling deleteDetectionType.');
            }
            // verify required parameter 'detectionTypeId' is not null or undefined
            if (detectionTypeId === null || detectionTypeId === undefined) {
                throw new RequiredError('detectionTypeId','Required parameter detectionTypeId was null or undefined when calling deleteDetectionType.');
            }
            const localVarPath = `/v1/organizations/{org_id}/agrifields/{agrifield_id}/detection-types/{detection_type_id}`
                .replace(`{${"org_id"}}`, encodeURIComponent(String(orgId)))
                .replace(`{${"agrifield_id"}}`, encodeURIComponent(String(agrifieldId)))
                .replace(`{${"detection_type_id"}}`, encodeURIComponent(String(detectionTypeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Detection Type
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agriculture Field ID
         * @param {string} detectionTypeId Detection Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDetectionType: async (orgId: string, agrifieldId: string, detectionTypeId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgId' is not null or undefined
            if (orgId === null || orgId === undefined) {
                throw new RequiredError('orgId','Required parameter orgId was null or undefined when calling getDetectionType.');
            }
            // verify required parameter 'agrifieldId' is not null or undefined
            if (agrifieldId === null || agrifieldId === undefined) {
                throw new RequiredError('agrifieldId','Required parameter agrifieldId was null or undefined when calling getDetectionType.');
            }
            // verify required parameter 'detectionTypeId' is not null or undefined
            if (detectionTypeId === null || detectionTypeId === undefined) {
                throw new RequiredError('detectionTypeId','Required parameter detectionTypeId was null or undefined when calling getDetectionType.');
            }
            const localVarPath = `/v1/organizations/{org_id}/agrifields/{agrifield_id}/detection-types/{detection_type_id}`
                .replace(`{${"org_id"}}`, encodeURIComponent(String(orgId)))
                .replace(`{${"agrifield_id"}}`, encodeURIComponent(String(agrifieldId)))
                .replace(`{${"detection_type_id"}}`, encodeURIComponent(String(detectionTypeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Detection Types
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agriculture Field ID
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDetectionTypes: async (orgId: string, agrifieldId: string, page?: number, limit?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgId' is not null or undefined
            if (orgId === null || orgId === undefined) {
                throw new RequiredError('orgId','Required parameter orgId was null or undefined when calling listDetectionTypes.');
            }
            // verify required parameter 'agrifieldId' is not null or undefined
            if (agrifieldId === null || agrifieldId === undefined) {
                throw new RequiredError('agrifieldId','Required parameter agrifieldId was null or undefined when calling listDetectionTypes.');
            }
            const localVarPath = `/v1/organizations/{org_id}/agrifields/{agrifield_id}/detection-types`
                .replace(`{${"org_id"}}`, encodeURIComponent(String(orgId)))
                .replace(`{${"agrifield_id"}}`, encodeURIComponent(String(agrifieldId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Detection Type
         * @param {DetectionTypeUpdatePayload} body 
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agriculture Field ID
         * @param {string} detectionTypeId Detection Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateDetectionType: async (body: DetectionTypeUpdatePayload, orgId: string, agrifieldId: string, detectionTypeId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateDetectionType.');
            }
            // verify required parameter 'orgId' is not null or undefined
            if (orgId === null || orgId === undefined) {
                throw new RequiredError('orgId','Required parameter orgId was null or undefined when calling updateDetectionType.');
            }
            // verify required parameter 'agrifieldId' is not null or undefined
            if (agrifieldId === null || agrifieldId === undefined) {
                throw new RequiredError('agrifieldId','Required parameter agrifieldId was null or undefined when calling updateDetectionType.');
            }
            // verify required parameter 'detectionTypeId' is not null or undefined
            if (detectionTypeId === null || detectionTypeId === undefined) {
                throw new RequiredError('detectionTypeId','Required parameter detectionTypeId was null or undefined when calling updateDetectionType.');
            }
            const localVarPath = `/v1/organizations/{org_id}/agrifields/{agrifield_id}/detection-types/{detection_type_id}`
                .replace(`{${"org_id"}}`, encodeURIComponent(String(orgId)))
                .replace(`{${"agrifield_id"}}`, encodeURIComponent(String(agrifieldId)))
                .replace(`{${"detection_type_id"}}`, encodeURIComponent(String(detectionTypeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DetectionTypesApi - functional programming interface
 * @export
 */
export const DetectionTypesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Detection Type
         * @param {DetectionTypeCreatePayload} body 
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agriculture Field ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDetectionType(body: DetectionTypeCreatePayload, orgId: string, agrifieldId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DetectionType>>> {
            const localVarAxiosArgs = await DetectionTypesApiAxiosParamCreator(configuration).createDetectionType(body, orgId, agrifieldId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Delete Detection Type
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agriculture Field ID
         * @param {string} detectionTypeId Detection Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDetectionType(orgId: string, agrifieldId: string, detectionTypeId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<StatusResponse>>> {
            const localVarAxiosArgs = await DetectionTypesApiAxiosParamCreator(configuration).deleteDetectionType(orgId, agrifieldId, detectionTypeId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get Detection Type
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agriculture Field ID
         * @param {string} detectionTypeId Detection Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDetectionType(orgId: string, agrifieldId: string, detectionTypeId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DetectionType>>> {
            const localVarAxiosArgs = await DetectionTypesApiAxiosParamCreator(configuration).getDetectionType(orgId, agrifieldId, detectionTypeId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary List Detection Types
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agriculture Field ID
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listDetectionTypes(orgId: string, agrifieldId: string, page?: number, limit?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PaginatedResponse>>> {
            const localVarAxiosArgs = await DetectionTypesApiAxiosParamCreator(configuration).listDetectionTypes(orgId, agrifieldId, page, limit, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Update Detection Type
         * @param {DetectionTypeUpdatePayload} body 
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agriculture Field ID
         * @param {string} detectionTypeId Detection Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateDetectionType(body: DetectionTypeUpdatePayload, orgId: string, agrifieldId: string, detectionTypeId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DetectionType>>> {
            const localVarAxiosArgs = await DetectionTypesApiAxiosParamCreator(configuration).updateDetectionType(body, orgId, agrifieldId, detectionTypeId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DetectionTypesApi - factory interface
 * @export
 */
export const DetectionTypesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Create Detection Type
         * @param {DetectionTypeCreatePayload} body 
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agriculture Field ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDetectionType(body: DetectionTypeCreatePayload, orgId: string, agrifieldId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<DetectionType>> {
            return DetectionTypesApiFp(configuration).createDetectionType(body, orgId, agrifieldId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Detection Type
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agriculture Field ID
         * @param {string} detectionTypeId Detection Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDetectionType(orgId: string, agrifieldId: string, detectionTypeId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StatusResponse>> {
            return DetectionTypesApiFp(configuration).deleteDetectionType(orgId, agrifieldId, detectionTypeId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Detection Type
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agriculture Field ID
         * @param {string} detectionTypeId Detection Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDetectionType(orgId: string, agrifieldId: string, detectionTypeId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<DetectionType>> {
            return DetectionTypesApiFp(configuration).getDetectionType(orgId, agrifieldId, detectionTypeId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Detection Types
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agriculture Field ID
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listDetectionTypes(orgId: string, agrifieldId: string, page?: number, limit?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<PaginatedResponse>> {
            return DetectionTypesApiFp(configuration).listDetectionTypes(orgId, agrifieldId, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Detection Type
         * @param {DetectionTypeUpdatePayload} body 
         * @param {string} orgId Organization ID
         * @param {string} agrifieldId Agriculture Field ID
         * @param {string} detectionTypeId Detection Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateDetectionType(body: DetectionTypeUpdatePayload, orgId: string, agrifieldId: string, detectionTypeId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<DetectionType>> {
            return DetectionTypesApiFp(configuration).updateDetectionType(body, orgId, agrifieldId, detectionTypeId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DetectionTypesApi - object-oriented interface
 * @export
 * @class DetectionTypesApi
 * @extends {BaseAPI}
 */
export class DetectionTypesApi extends BaseAPI {
    /**
     * 
     * @summary Create Detection Type
     * @param {DetectionTypeCreatePayload} body 
     * @param {string} orgId Organization ID
     * @param {string} agrifieldId Agriculture Field ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DetectionTypesApi
     */
    public async createDetectionType(body: DetectionTypeCreatePayload, orgId: string, agrifieldId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<DetectionType>> {
        return DetectionTypesApiFp(this.configuration).createDetectionType(body, orgId, agrifieldId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Delete Detection Type
     * @param {string} orgId Organization ID
     * @param {string} agrifieldId Agriculture Field ID
     * @param {string} detectionTypeId Detection Type ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DetectionTypesApi
     */
    public async deleteDetectionType(orgId: string, agrifieldId: string, detectionTypeId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<StatusResponse>> {
        return DetectionTypesApiFp(this.configuration).deleteDetectionType(orgId, agrifieldId, detectionTypeId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get Detection Type
     * @param {string} orgId Organization ID
     * @param {string} agrifieldId Agriculture Field ID
     * @param {string} detectionTypeId Detection Type ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DetectionTypesApi
     */
    public async getDetectionType(orgId: string, agrifieldId: string, detectionTypeId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<DetectionType>> {
        return DetectionTypesApiFp(this.configuration).getDetectionType(orgId, agrifieldId, detectionTypeId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary List Detection Types
     * @param {string} orgId Organization ID
     * @param {string} agrifieldId Agriculture Field ID
     * @param {number} [page] Page number
     * @param {number} [limit] Items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DetectionTypesApi
     */
    public async listDetectionTypes(orgId: string, agrifieldId: string, page?: number, limit?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<PaginatedResponse>> {
        return DetectionTypesApiFp(this.configuration).listDetectionTypes(orgId, agrifieldId, page, limit, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Update Detection Type
     * @param {DetectionTypeUpdatePayload} body 
     * @param {string} orgId Organization ID
     * @param {string} agrifieldId Agriculture Field ID
     * @param {string} detectionTypeId Detection Type ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DetectionTypesApi
     */
    public async updateDetectionType(body: DetectionTypeUpdatePayload, orgId: string, agrifieldId: string, detectionTypeId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<DetectionType>> {
        return DetectionTypesApiFp(this.configuration).updateDetectionType(body, orgId, agrifieldId, detectionTypeId, options).then((request) => request(this.axios, this.basePath));
    }
}
