/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { DetectionText } from '../models';
import { DetectionTextCreatePayload } from '../models';
import { DetectionTextUpdatePayload } from '../models';
import { ErrorResponse } from '../models';
import { PaginatedResponse } from '../models';
import { StatusResponse } from '../models';
/**
 * DetectionTextsApi - axios parameter creator
 * @export
 */
export const DetectionTextsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Detection Text
         * @param {DetectionTextCreatePayload} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDetectionText: async (body: DetectionTextCreatePayload, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createDetectionText.');
            }
            const localVarPath = `/v1/detection-texts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Detection Text
         * @param {string} detectionTextId Detection Text ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDetectionText: async (detectionTextId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'detectionTextId' is not null or undefined
            if (detectionTextId === null || detectionTextId === undefined) {
                throw new RequiredError('detectionTextId','Required parameter detectionTextId was null or undefined when calling deleteDetectionText.');
            }
            const localVarPath = `/v1/detection-texts/{detection_text_id}`
                .replace(`{${"detection_text_id"}}`, encodeURIComponent(String(detectionTextId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Detection Text
         * @param {string} detectionTextId Detection Text ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDetectionText: async (detectionTextId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'detectionTextId' is not null or undefined
            if (detectionTextId === null || detectionTextId === undefined) {
                throw new RequiredError('detectionTextId','Required parameter detectionTextId was null or undefined when calling getDetectionText.');
            }
            const localVarPath = `/v1/detection-texts/{detection_text_id}`
                .replace(`{${"detection_text_id"}}`, encodeURIComponent(String(detectionTextId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Detection Texts
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDetectionTexts: async (page?: number, limit?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/detection-texts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Detection Text
         * @param {DetectionTextUpdatePayload} body 
         * @param {string} detectionTextId Detection Text ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateDetectionText: async (body: DetectionTextUpdatePayload, detectionTextId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateDetectionText.');
            }
            // verify required parameter 'detectionTextId' is not null or undefined
            if (detectionTextId === null || detectionTextId === undefined) {
                throw new RequiredError('detectionTextId','Required parameter detectionTextId was null or undefined when calling updateDetectionText.');
            }
            const localVarPath = `/v1/detection-texts/{detection_text_id}`
                .replace(`{${"detection_text_id"}}`, encodeURIComponent(String(detectionTextId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DetectionTextsApi - functional programming interface
 * @export
 */
export const DetectionTextsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Detection Text
         * @param {DetectionTextCreatePayload} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDetectionText(body: DetectionTextCreatePayload, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DetectionText>>> {
            const localVarAxiosArgs = await DetectionTextsApiAxiosParamCreator(configuration).createDetectionText(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Delete Detection Text
         * @param {string} detectionTextId Detection Text ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDetectionText(detectionTextId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<StatusResponse>>> {
            const localVarAxiosArgs = await DetectionTextsApiAxiosParamCreator(configuration).deleteDetectionText(detectionTextId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get Detection Text
         * @param {string} detectionTextId Detection Text ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDetectionText(detectionTextId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DetectionText>>> {
            const localVarAxiosArgs = await DetectionTextsApiAxiosParamCreator(configuration).getDetectionText(detectionTextId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary List Detection Texts
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listDetectionTexts(page?: number, limit?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PaginatedResponse>>> {
            const localVarAxiosArgs = await DetectionTextsApiAxiosParamCreator(configuration).listDetectionTexts(page, limit, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Update Detection Text
         * @param {DetectionTextUpdatePayload} body 
         * @param {string} detectionTextId Detection Text ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateDetectionText(body: DetectionTextUpdatePayload, detectionTextId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DetectionText>>> {
            const localVarAxiosArgs = await DetectionTextsApiAxiosParamCreator(configuration).updateDetectionText(body, detectionTextId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DetectionTextsApi - factory interface
 * @export
 */
export const DetectionTextsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Create Detection Text
         * @param {DetectionTextCreatePayload} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDetectionText(body: DetectionTextCreatePayload, options?: AxiosRequestConfig): Promise<AxiosResponse<DetectionText>> {
            return DetectionTextsApiFp(configuration).createDetectionText(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Detection Text
         * @param {string} detectionTextId Detection Text ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDetectionText(detectionTextId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StatusResponse>> {
            return DetectionTextsApiFp(configuration).deleteDetectionText(detectionTextId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Detection Text
         * @param {string} detectionTextId Detection Text ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDetectionText(detectionTextId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<DetectionText>> {
            return DetectionTextsApiFp(configuration).getDetectionText(detectionTextId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Detection Texts
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listDetectionTexts(page?: number, limit?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<PaginatedResponse>> {
            return DetectionTextsApiFp(configuration).listDetectionTexts(page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Detection Text
         * @param {DetectionTextUpdatePayload} body 
         * @param {string} detectionTextId Detection Text ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateDetectionText(body: DetectionTextUpdatePayload, detectionTextId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<DetectionText>> {
            return DetectionTextsApiFp(configuration).updateDetectionText(body, detectionTextId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DetectionTextsApi - object-oriented interface
 * @export
 * @class DetectionTextsApi
 * @extends {BaseAPI}
 */
export class DetectionTextsApi extends BaseAPI {
    /**
     * 
     * @summary Create Detection Text
     * @param {DetectionTextCreatePayload} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DetectionTextsApi
     */
    public async createDetectionText(body: DetectionTextCreatePayload, options?: AxiosRequestConfig) : Promise<AxiosResponse<DetectionText>> {
        return DetectionTextsApiFp(this.configuration).createDetectionText(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Delete Detection Text
     * @param {string} detectionTextId Detection Text ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DetectionTextsApi
     */
    public async deleteDetectionText(detectionTextId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<StatusResponse>> {
        return DetectionTextsApiFp(this.configuration).deleteDetectionText(detectionTextId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get Detection Text
     * @param {string} detectionTextId Detection Text ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DetectionTextsApi
     */
    public async getDetectionText(detectionTextId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<DetectionText>> {
        return DetectionTextsApiFp(this.configuration).getDetectionText(detectionTextId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary List Detection Texts
     * @param {number} [page] Page number
     * @param {number} [limit] Items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DetectionTextsApi
     */
    public async listDetectionTexts(page?: number, limit?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<PaginatedResponse>> {
        return DetectionTextsApiFp(this.configuration).listDetectionTexts(page, limit, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Update Detection Text
     * @param {DetectionTextUpdatePayload} body 
     * @param {string} detectionTextId Detection Text ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DetectionTextsApi
     */
    public async updateDetectionText(body: DetectionTextUpdatePayload, detectionTextId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<DetectionText>> {
        return DetectionTextsApiFp(this.configuration).updateDetectionText(body, detectionTextId, options).then((request) => request(this.axios, this.basePath));
    }
}
