/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// @ts-ignore
import { BASE_PATH, RequestArgs, BaseAPI, RequiredError } from '../base';
import { HarvestType } from '../models';
import { HarvestTypeCreatePayload } from '../models';
import { HarvestTypeUpdatePayload } from '../models';
import { PaginatedResponse } from '../models';
import { StatusResponse } from '../models';

export const HarvestTypesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        createHarvestType: async (body: HarvestTypeCreatePayload, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createHarvestType.');
            }
            const localVarPath = `/v1/harvest-types`;
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            const baseOptions = configuration ? configuration.baseOptions : undefined;
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;

            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = JSON.stringify(body !== undefined ? body : {});

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        deleteHarvestType: async (harvestTypeId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            if (harvestTypeId === null || harvestTypeId === undefined) {
                throw new RequiredError('harvestTypeId','Required parameter harvestTypeId was null or undefined when calling deleteHarvestType.');
            }
            const localVarPath = `/v1/harvest-types/{harvest_type_id}`
                .replace(`{${"harvest_type_id"}}`, encodeURIComponent(String(harvestTypeId)));
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            const baseOptions = configuration ? configuration.baseOptions : undefined;
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;

            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        getHarvestType: async (harvestTypeId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            if (harvestTypeId === null || harvestTypeId === undefined) {
                throw new RequiredError('harvestTypeId','Required parameter harvestTypeId was null or undefined when calling getHarvestType.');
            }
            const localVarPath = `/v1/harvest-types/{harvest_type_id}`
                .replace(`{${"harvest_type_id"}}`, encodeURIComponent(String(harvestTypeId)));
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            const baseOptions = configuration ? configuration.baseOptions : undefined;
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;

            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        listHarvestTypes: async (page?: number, limit?: number, active?: boolean, includeInactive?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/harvest-types`;
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            const baseOptions = configuration ? configuration.baseOptions : undefined;
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }
            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }
            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }
            if (active !== undefined) {
                localVarQueryParameter['active'] = active;
            }
            if (includeInactive !== undefined) {
                localVarQueryParameter['include_inactive'] = includeInactive;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            if (options.params) {
                for (const key in options.params) {
                    query.set(key, options.params[key]);
                }
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        updateHarvestType: async (body: HarvestTypeUpdatePayload, harvestTypeId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateHarvestType.');
            }
            if (harvestTypeId === null || harvestTypeId === undefined) {
                throw new RequiredError('harvestTypeId','Required parameter harvestTypeId was null or undefined when calling updateHarvestType.');
            }
            const localVarPath = `/v1/harvest-types/{harvest_type_id}`
                .replace(`{${"harvest_type_id"}}`, encodeURIComponent(String(harvestTypeId)));
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            const baseOptions = configuration ? configuration.baseOptions : undefined;
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;

            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = JSON.stringify(body !== undefined ? body : {});

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

export const HarvestTypesApiFp = function(configuration?: Configuration) {
    return {
        async createHarvestType(body: HarvestTypeCreatePayload, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<HarvestType>>> {
            const localVarAxiosArgs = await HarvestTypesApiAxiosParamCreator(configuration).createHarvestType(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => axios.request({...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url});
        },
        async deleteHarvestType(harvestTypeId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<StatusResponse>>> {
            const localVarAxiosArgs = await HarvestTypesApiAxiosParamCreator(configuration).deleteHarvestType(harvestTypeId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => axios.request({...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url});
        },
        async getHarvestType(harvestTypeId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<HarvestType>>> {
            const localVarAxiosArgs = await HarvestTypesApiAxiosParamCreator(configuration).getHarvestType(harvestTypeId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => axios.request({...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url});
        },
        async listHarvestTypes(page?: number, limit?: number, active?: boolean, includeInactive?: boolean, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PaginatedResponse>>> {
            const localVarAxiosArgs = await HarvestTypesApiAxiosParamCreator(configuration).listHarvestTypes(page, limit, active, includeInactive, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => axios.request({...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url});
        },
        async updateHarvestType(body: HarvestTypeUpdatePayload, harvestTypeId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<HarvestType>>> {
            const localVarAxiosArgs = await HarvestTypesApiAxiosParamCreator(configuration).updateHarvestType(body, harvestTypeId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => axios.request({...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url});
        },
    }
};

export const HarvestTypesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        async createHarvestType(body: HarvestTypeCreatePayload, options?: AxiosRequestConfig): Promise<AxiosResponse<HarvestType>> {
            return HarvestTypesApiFp(configuration).createHarvestType(body, options).then((request) => request(axios, basePath));
        },
        async deleteHarvestType(harvestTypeId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StatusResponse>> {
            return HarvestTypesApiFp(configuration).deleteHarvestType(harvestTypeId, options).then((request) => request(axios, basePath));
        },
        async getHarvestType(harvestTypeId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<HarvestType>> {
            return HarvestTypesApiFp(configuration).getHarvestType(harvestTypeId, options).then((request) => request(axios, basePath));
        },
        async listHarvestTypes(page?: number, limit?: number, active?: boolean, includeInactive?: boolean, options?: AxiosRequestConfig): Promise<AxiosResponse<PaginatedResponse>> {
            return HarvestTypesApiFp(configuration).listHarvestTypes(page, limit, active, includeInactive, options).then((request) => request(axios, basePath));
        },
        async updateHarvestType(body: HarvestTypeUpdatePayload, harvestTypeId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<HarvestType>> {
            return HarvestTypesApiFp(configuration).updateHarvestType(body, harvestTypeId, options).then((request) => request(axios, basePath));
        },
    };
};

export class HarvestTypesApi extends BaseAPI {
    public async createHarvestType(body: HarvestTypeCreatePayload, options?: AxiosRequestConfig) : Promise<AxiosResponse<HarvestType>> {
        return HarvestTypesApiFp(this.configuration).createHarvestType(body, options).then((request) => request(this.axios, this.basePath));
    }
    public async deleteHarvestType(harvestTypeId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<StatusResponse>> {
        return HarvestTypesApiFp(this.configuration).deleteHarvestType(harvestTypeId, options).then((request) => request(this.axios, this.basePath));
    }
    public async getHarvestType(harvestTypeId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<HarvestType>> {
        return HarvestTypesApiFp(this.configuration).getHarvestType(harvestTypeId, options).then((request) => request(this.axios, this.basePath));
    }
    public async listHarvestTypes(page?: number, limit?: number, active?: boolean, includeInactive?: boolean, options?: AxiosRequestConfig) : Promise<AxiosResponse<PaginatedResponse>> {
        return HarvestTypesApiFp(this.configuration).listHarvestTypes(page, limit, active, includeInactive, options).then((request) => request(this.axios, this.basePath));
    }
    public async updateHarvestType(body: HarvestTypeUpdatePayload, harvestTypeId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<HarvestType>> {
        return HarvestTypesApiFp(this.configuration).updateHarvestType(body, harvestTypeId, options).then((request) => request(this.axios, this.basePath));
    }
}
