/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ErrorResponse } from '../models';
import { Invitation } from '../models';
import { InvitationAcceptPayload } from '../models';
import { InvitationCreatePayload } from '../models';
import { InvitationValidateResponse } from '../models';
import { StatusResponse } from '../models';
/**
 * InvitationsApi - axios parameter creator
 * @export
 */
export const InvitationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Accept an invitation (user must be authenticated) Adds user to organization and assigns role  Special case: When a company owner accepts an invitation from an agronomist, they may need to provide orgId if they already have an organization. If they don't have an organization yet, they need to create one first.
         * @summary Accept Invitation
         * @param {InvitationAcceptPayload} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        acceptInvitation: async (body: InvitationAcceptPayload, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling acceptInvitation.');
            }
            const localVarPath = `/v1/invitations/accept`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new invitation  Two scenarios: 1. Standard invitation: orgId provided in payload, invitee joins that org 2. Agronomist → New Company Owner: orgId is null in payload, company owner creates org later  Permissions: - Company Owner can invite managers/standard/agronomists - Agronomist can invite company owners - Company Manager can invite standard users
         * @summary Create Invitation
         * @param {InvitationCreatePayload} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createInvitation: async (body: InvitationCreatePayload, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createInvitation.');
            }
            const localVarPath = `/v1/invitations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Decline an invitation (no auth required - uses token)
         * @summary Decline Invitation
         * @param {InvitationAcceptPayload} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        declineInvitation: async (body: InvitationAcceptPayload, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling declineInvitation.');
            }
            const localVarPath = `/v1/invitations/decline`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * List all pending invitations for the authenticated user Matches by email from Keycloak profile
         * @summary List My Invitations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMyInvitations: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/invitations/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * List all invitations for an organization Filter by status: pending, accepted, declined, expired
         * @summary List Organization Invitations
         * @param {string} orgId Organization ID
         * @param {string} [status] Filter by status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listOrganizationInvitations: async (orgId: string, status?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orgId' is not null or undefined
            if (orgId === null || orgId === undefined) {
                throw new RequiredError('orgId','Required parameter orgId was null or undefined when calling listOrganizationInvitations.');
            }
            const localVarPath = `/v1/invitations/byOrg`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (orgId !== undefined) {
                localVarQueryParameter['org_id'] = orgId;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Resend invitation email (generates new token)
         * @summary Resend Invitation
         * @param {string} invitationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resendInvitation: async (invitationId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'invitationId' is not null or undefined
            if (invitationId === null || invitationId === undefined) {
                throw new RequiredError('invitationId','Required parameter invitationId was null or undefined when calling resendInvitation.');
            }
            const localVarPath = `/v1/invitations/{invitation_id}/resend`
                .replace(`{${"invitation_id"}}`, encodeURIComponent(String(invitationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Revoke (soft delete) a pending invitation
         * @summary Revoke Invitation
         * @param {string} invitationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        revokeInvitation: async (invitationId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'invitationId' is not null or undefined
            if (invitationId === null || invitationId === undefined) {
                throw new RequiredError('invitationId','Required parameter invitationId was null or undefined when calling revokeInvitation.');
            }
            const localVarPath = `/v1/invitations/{invitation_id}`
                .replace(`{${"invitation_id"}}`, encodeURIComponent(String(invitationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Validate an invitation token (public endpoint, no auth required) Returns invitation details if valid
         * @summary Validate Invitation Token
         * @param {string} token Invitation token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        validateInvitationToken: async (token: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            if (token === null || token === undefined) {
                throw new RequiredError('token','Required parameter token was null or undefined when calling validateInvitationToken.');
            }
            const localVarPath = `/v1/invitations/validate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (token !== undefined) {
                localVarQueryParameter['token'] = token;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InvitationsApi - functional programming interface
 * @export
 */
export const InvitationsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Accept an invitation (user must be authenticated) Adds user to organization and assigns role  Special case: When a company owner accepts an invitation from an agronomist, they may need to provide orgId if they already have an organization. If they don't have an organization yet, they need to create one first.
         * @summary Accept Invitation
         * @param {InvitationAcceptPayload} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async acceptInvitation(body: InvitationAcceptPayload, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<StatusResponse>>> {
            const localVarAxiosArgs = await InvitationsApiAxiosParamCreator(configuration).acceptInvitation(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Create a new invitation  Two scenarios: 1. Standard invitation: orgId provided in payload, invitee joins that org 2. Agronomist → New Company Owner: orgId is null in payload, company owner creates org later  Permissions: - Company Owner can invite managers/standard/agronomists - Agronomist can invite company owners - Company Manager can invite standard users
         * @summary Create Invitation
         * @param {InvitationCreatePayload} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createInvitation(body: InvitationCreatePayload, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Invitation>>> {
            const localVarAxiosArgs = await InvitationsApiAxiosParamCreator(configuration).createInvitation(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Decline an invitation (no auth required - uses token)
         * @summary Decline Invitation
         * @param {InvitationAcceptPayload} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async declineInvitation(body: InvitationAcceptPayload, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<StatusResponse>>> {
            const localVarAxiosArgs = await InvitationsApiAxiosParamCreator(configuration).declineInvitation(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * List all pending invitations for the authenticated user Matches by email from Keycloak profile
         * @summary List My Invitations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listMyInvitations(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<Invitation>>>> {
            const localVarAxiosArgs = await InvitationsApiAxiosParamCreator(configuration).listMyInvitations(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * List all invitations for an organization Filter by status: pending, accepted, declined, expired
         * @summary List Organization Invitations
         * @param {string} orgId Organization ID
         * @param {string} [status] Filter by status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listOrganizationInvitations(orgId: string, status?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<Invitation>>>> {
            const localVarAxiosArgs = await InvitationsApiAxiosParamCreator(configuration).listOrganizationInvitations(orgId, status, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Resend invitation email (generates new token)
         * @summary Resend Invitation
         * @param {string} invitationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resendInvitation(invitationId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<StatusResponse>>> {
            const localVarAxiosArgs = await InvitationsApiAxiosParamCreator(configuration).resendInvitation(invitationId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Revoke (soft delete) a pending invitation
         * @summary Revoke Invitation
         * @param {string} invitationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async revokeInvitation(invitationId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<StatusResponse>>> {
            const localVarAxiosArgs = await InvitationsApiAxiosParamCreator(configuration).revokeInvitation(invitationId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Validate an invitation token (public endpoint, no auth required) Returns invitation details if valid
         * @summary Validate Invitation Token
         * @param {string} token Invitation token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validateInvitationToken(token: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InvitationValidateResponse>>> {
            const localVarAxiosArgs = await InvitationsApiAxiosParamCreator(configuration).validateInvitationToken(token, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * InvitationsApi - factory interface
 * @export
 */
export const InvitationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Accept an invitation (user must be authenticated) Adds user to organization and assigns role  Special case: When a company owner accepts an invitation from an agronomist, they may need to provide orgId if they already have an organization. If they don't have an organization yet, they need to create one first.
         * @summary Accept Invitation
         * @param {InvitationAcceptPayload} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async acceptInvitation(body: InvitationAcceptPayload, options?: AxiosRequestConfig): Promise<AxiosResponse<StatusResponse>> {
            return InvitationsApiFp(configuration).acceptInvitation(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new invitation  Two scenarios: 1. Standard invitation: orgId provided in payload, invitee joins that org 2. Agronomist → New Company Owner: orgId is null in payload, company owner creates org later  Permissions: - Company Owner can invite managers/standard/agronomists - Agronomist can invite company owners - Company Manager can invite standard users
         * @summary Create Invitation
         * @param {InvitationCreatePayload} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createInvitation(body: InvitationCreatePayload, options?: AxiosRequestConfig): Promise<AxiosResponse<Invitation>> {
            return InvitationsApiFp(configuration).createInvitation(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Decline an invitation (no auth required - uses token)
         * @summary Decline Invitation
         * @param {InvitationAcceptPayload} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async declineInvitation(body: InvitationAcceptPayload, options?: AxiosRequestConfig): Promise<AxiosResponse<StatusResponse>> {
            return InvitationsApiFp(configuration).declineInvitation(body, options).then((request) => request(axios, basePath));
        },
        /**
         * List all pending invitations for the authenticated user Matches by email from Keycloak profile
         * @summary List My Invitations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listMyInvitations(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<Invitation>>> {
            return InvitationsApiFp(configuration).listMyInvitations(options).then((request) => request(axios, basePath));
        },
        /**
         * List all invitations for an organization Filter by status: pending, accepted, declined, expired
         * @summary List Organization Invitations
         * @param {string} orgId Organization ID
         * @param {string} [status] Filter by status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listOrganizationInvitations(orgId: string, status?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<Invitation>>> {
            return InvitationsApiFp(configuration).listOrganizationInvitations(orgId, status, options).then((request) => request(axios, basePath));
        },
        /**
         * Resend invitation email (generates new token)
         * @summary Resend Invitation
         * @param {string} invitationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resendInvitation(invitationId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StatusResponse>> {
            return InvitationsApiFp(configuration).resendInvitation(invitationId, options).then((request) => request(axios, basePath));
        },
        /**
         * Revoke (soft delete) a pending invitation
         * @summary Revoke Invitation
         * @param {string} invitationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async revokeInvitation(invitationId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StatusResponse>> {
            return InvitationsApiFp(configuration).revokeInvitation(invitationId, options).then((request) => request(axios, basePath));
        },
        /**
         * Validate an invitation token (public endpoint, no auth required) Returns invitation details if valid
         * @summary Validate Invitation Token
         * @param {string} token Invitation token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async validateInvitationToken(token: string, options?: AxiosRequestConfig): Promise<AxiosResponse<InvitationValidateResponse>> {
            return InvitationsApiFp(configuration).validateInvitationToken(token, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InvitationsApi - object-oriented interface
 * @export
 * @class InvitationsApi
 * @extends {BaseAPI}
 */
export class InvitationsApi extends BaseAPI {
    /**
     * Accept an invitation (user must be authenticated) Adds user to organization and assigns role  Special case: When a company owner accepts an invitation from an agronomist, they may need to provide orgId if they already have an organization. If they don't have an organization yet, they need to create one first.
     * @summary Accept Invitation
     * @param {InvitationAcceptPayload} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvitationsApi
     */
    public async acceptInvitation(body: InvitationAcceptPayload, options?: AxiosRequestConfig) : Promise<AxiosResponse<StatusResponse>> {
        return InvitationsApiFp(this.configuration).acceptInvitation(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Create a new invitation  Two scenarios: 1. Standard invitation: orgId provided in payload, invitee joins that org 2. Agronomist → New Company Owner: orgId is null in payload, company owner creates org later  Permissions: - Company Owner can invite managers/standard/agronomists - Agronomist can invite company owners - Company Manager can invite standard users
     * @summary Create Invitation
     * @param {InvitationCreatePayload} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvitationsApi
     */
    public async createInvitation(body: InvitationCreatePayload, options?: AxiosRequestConfig) : Promise<AxiosResponse<Invitation>> {
        return InvitationsApiFp(this.configuration).createInvitation(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Decline an invitation (no auth required - uses token)
     * @summary Decline Invitation
     * @param {InvitationAcceptPayload} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvitationsApi
     */
    public async declineInvitation(body: InvitationAcceptPayload, options?: AxiosRequestConfig) : Promise<AxiosResponse<StatusResponse>> {
        return InvitationsApiFp(this.configuration).declineInvitation(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * List all pending invitations for the authenticated user Matches by email from Keycloak profile
     * @summary List My Invitations
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvitationsApi
     */
    public async listMyInvitations(options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<Invitation>>> {
        return InvitationsApiFp(this.configuration).listMyInvitations(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * List all invitations for an organization Filter by status: pending, accepted, declined, expired
     * @summary List Organization Invitations
     * @param {string} orgId Organization ID
     * @param {string} [status] Filter by status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvitationsApi
     */
    public async listOrganizationInvitations(orgId: string, status?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<Invitation>>> {
        return InvitationsApiFp(this.configuration).listOrganizationInvitations(orgId, status, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Resend invitation email (generates new token)
     * @summary Resend Invitation
     * @param {string} invitationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvitationsApi
     */
    public async resendInvitation(invitationId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<StatusResponse>> {
        return InvitationsApiFp(this.configuration).resendInvitation(invitationId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Revoke (soft delete) a pending invitation
     * @summary Revoke Invitation
     * @param {string} invitationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvitationsApi
     */
    public async revokeInvitation(invitationId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<StatusResponse>> {
        return InvitationsApiFp(this.configuration).revokeInvitation(invitationId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Validate an invitation token (public endpoint, no auth required) Returns invitation details if valid
     * @summary Validate Invitation Token
     * @param {string} token Invitation token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvitationsApi
     */
    public async validateInvitationToken(token: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<InvitationValidateResponse>> {
        return InvitationsApiFp(this.configuration).validateInvitationToken(token, options).then((request) => request(this.axios, this.basePath));
    }
}
