/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ErrorResponse } from '../models';
import { ObservationType } from '../models';
import { ObservationTypeCreatePayload } from '../models';
import { ObservationTypeUpdatePayload } from '../models';
import { PaginatedResponse } from '../models';
import { StatusResponse } from '../models';
/**
 * ObservationTypesApi - axios parameter creator
 * @export
 */
export const ObservationTypesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Observation Type
         * @param {ObservationTypeCreatePayload} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createObservationType: async (body: ObservationTypeCreatePayload, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createObservationType.');
            }
            const localVarPath = `/v1/observation-types`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Observation Type
         * @param {string} observationTypeId Observation Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteObservationType: async (observationTypeId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'observationTypeId' is not null or undefined
            if (observationTypeId === null || observationTypeId === undefined) {
                throw new RequiredError('observationTypeId','Required parameter observationTypeId was null or undefined when calling deleteObservationType.');
            }
            const localVarPath = `/v1/observation-types/{observation_type_id}`
                .replace(`{${"observation_type_id"}}`, encodeURIComponent(String(observationTypeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Observation Type
         * @param {string} observationTypeId Observation Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getObservationType: async (observationTypeId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'observationTypeId' is not null or undefined
            if (observationTypeId === null || observationTypeId === undefined) {
                throw new RequiredError('observationTypeId','Required parameter observationTypeId was null or undefined when calling getObservationType.');
            }
            const localVarPath = `/v1/observation-types/{observation_type_id}`
                .replace(`{${"observation_type_id"}}`, encodeURIComponent(String(observationTypeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Observation Types
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listObservationTypes: async (page?: number, limit?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/observation-types`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Observation Type
         * @param {ObservationTypeUpdatePayload} body 
         * @param {string} observationTypeId Observation Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateObservationType: async (body: ObservationTypeUpdatePayload, observationTypeId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateObservationType.');
            }
            // verify required parameter 'observationTypeId' is not null or undefined
            if (observationTypeId === null || observationTypeId === undefined) {
                throw new RequiredError('observationTypeId','Required parameter observationTypeId was null or undefined when calling updateObservationType.');
            }
            const localVarPath = `/v1/observation-types/{observation_type_id}`
                .replace(`{${"observation_type_id"}}`, encodeURIComponent(String(observationTypeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecurityChecker required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ObservationTypesApi - functional programming interface
 * @export
 */
export const ObservationTypesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Observation Type
         * @param {ObservationTypeCreatePayload} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createObservationType(body: ObservationTypeCreatePayload, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ObservationType>>> {
            const localVarAxiosArgs = await ObservationTypesApiAxiosParamCreator(configuration).createObservationType(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Delete Observation Type
         * @param {string} observationTypeId Observation Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteObservationType(observationTypeId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<StatusResponse>>> {
            const localVarAxiosArgs = await ObservationTypesApiAxiosParamCreator(configuration).deleteObservationType(observationTypeId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get Observation Type
         * @param {string} observationTypeId Observation Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getObservationType(observationTypeId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ObservationType>>> {
            const localVarAxiosArgs = await ObservationTypesApiAxiosParamCreator(configuration).getObservationType(observationTypeId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary List Observation Types
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listObservationTypes(page?: number, limit?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PaginatedResponse>>> {
            const localVarAxiosArgs = await ObservationTypesApiAxiosParamCreator(configuration).listObservationTypes(page, limit, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Update Observation Type
         * @param {ObservationTypeUpdatePayload} body 
         * @param {string} observationTypeId Observation Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateObservationType(body: ObservationTypeUpdatePayload, observationTypeId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ObservationType>>> {
            const localVarAxiosArgs = await ObservationTypesApiAxiosParamCreator(configuration).updateObservationType(body, observationTypeId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ObservationTypesApi - factory interface
 * @export
 */
export const ObservationTypesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Create Observation Type
         * @param {ObservationTypeCreatePayload} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createObservationType(body: ObservationTypeCreatePayload, options?: AxiosRequestConfig): Promise<AxiosResponse<ObservationType>> {
            return ObservationTypesApiFp(configuration).createObservationType(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Observation Type
         * @param {string} observationTypeId Observation Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteObservationType(observationTypeId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<StatusResponse>> {
            return ObservationTypesApiFp(configuration).deleteObservationType(observationTypeId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Observation Type
         * @param {string} observationTypeId Observation Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getObservationType(observationTypeId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<ObservationType>> {
            return ObservationTypesApiFp(configuration).getObservationType(observationTypeId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Observation Types
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listObservationTypes(page?: number, limit?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<PaginatedResponse>> {
            return ObservationTypesApiFp(configuration).listObservationTypes(page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Observation Type
         * @param {ObservationTypeUpdatePayload} body 
         * @param {string} observationTypeId Observation Type ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateObservationType(body: ObservationTypeUpdatePayload, observationTypeId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<ObservationType>> {
            return ObservationTypesApiFp(configuration).updateObservationType(body, observationTypeId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ObservationTypesApi - object-oriented interface
 * @export
 * @class ObservationTypesApi
 * @extends {BaseAPI}
 */
export class ObservationTypesApi extends BaseAPI {
    /**
     * 
     * @summary Create Observation Type
     * @param {ObservationTypeCreatePayload} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ObservationTypesApi
     */
    public async createObservationType(body: ObservationTypeCreatePayload, options?: AxiosRequestConfig) : Promise<AxiosResponse<ObservationType>> {
        return ObservationTypesApiFp(this.configuration).createObservationType(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Delete Observation Type
     * @param {string} observationTypeId Observation Type ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ObservationTypesApi
     */
    public async deleteObservationType(observationTypeId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<StatusResponse>> {
        return ObservationTypesApiFp(this.configuration).deleteObservationType(observationTypeId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get Observation Type
     * @param {string} observationTypeId Observation Type ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ObservationTypesApi
     */
    public async getObservationType(observationTypeId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<ObservationType>> {
        return ObservationTypesApiFp(this.configuration).getObservationType(observationTypeId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary List Observation Types
     * @param {number} [page] Page number
     * @param {number} [limit] Items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ObservationTypesApi
     */
    public async listObservationTypes(page?: number, limit?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<PaginatedResponse>> {
        return ObservationTypesApiFp(this.configuration).listObservationTypes(page, limit, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Update Observation Type
     * @param {ObservationTypeUpdatePayload} body 
     * @param {string} observationTypeId Observation Type ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ObservationTypesApi
     */
    public async updateObservationType(body: ObservationTypeUpdatePayload, observationTypeId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<ObservationType>> {
        return ObservationTypesApiFp(this.configuration).updateObservationType(body, observationTypeId, options).then((request) => request(this.axios, this.basePath));
    }
}
