/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Point } from './point';
 /**
 * 
 *
 * @export
 * @interface AgriFieldMutationPayload
 */
export interface AgriFieldMutationPayload {

    /**
     * @type {string}
     * @memberof AgriFieldMutationPayload
     */
    name: string;

    /**
     * @type {string}
     * @memberof AgriFieldMutationPayload
     */
    description: string;

    /**
     * @type {Array<Point>}
     * @memberof AgriFieldMutationPayload
     */
    map: Array<Point>;

    /**
     * @type {string}
     * @memberof AgriFieldMutationPayload
     */
    harvest: string;

    /**
     * @type {number}
     * @memberof AgriFieldMutationPayload
     */
    area: number;

    /**
     * @type {number}
     * @memberof AgriFieldMutationPayload
     */
    plants?: number;
}
