/* tslint:disable */
/* eslint-disable */
/**
 * Tornatura Core APIS
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Point } from './point';
 /**
 * 
 *
 * @export
 * @interface AgriField
 */
export interface AgriField {

    /**
     * @type {string}
     * @memberof AgriField
     */
    id: string;

    /**
     * @type {string}
     * @memberof AgriField
     */
    name: string;

    /**
     * @type {string}
     * @memberof AgriField
     */
    description: string;

    /**
     * @type {string}
     * @memberof AgriField
     */
    harvest: string;

    /**
     * @type {number}
     * @memberof AgriField
     */
    area: number;

    /**
     * @type {number}
     * @memberof AgriField
     */
    plants: number;

    /**
     * @type {string}
     * @memberof AgriField
     */
    variety: string;

    /**
     * @type {string}
     * @memberof AgriField
     */
    rotation: string;

    /**
     * @type {string}
     * @memberof AgriField
     */
    year?: string;

    /**
     * @type {string}
     * @memberof AgriField
     */
    irrigation: string;

    /**
     * @type {string}
     * @memberof AgriField
     */
    grassing: string;

    /**
     * @type {string}
     * @memberof AgriField
     */
    weaving: string;

    /**
     * @type {Array<Point>}
     * @memberof AgriField
     */
    map: Array<Point>;

    /**
     * @type {string}
     * @memberof AgriField
     */
    orgId: string;

    /**
     * @type {number}
     * @memberof AgriField
     */
    creationTime: number;

    /**
     * @type {number}
     * @memberof AgriField
     */
    lastUpdateTime: number;
}
