/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Point } from './point';
 /**
 * 
 *
 * @export
 * @interface DetectionPhoto
 */
export interface DetectionPhoto {

    /**
     * @type {string}
     * @memberof DetectionPhoto
     */
    caption: string;

    /**
     * @type {string}
     * @memberof DetectionPhoto
     */
    url: string;

    /**
     * @type {Point}
     * @memberof DetectionPhoto
     */
    position?: Point;
}
