/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Point } from './point';
 /**
 * 
 *
 * @export
 * @interface Detection
 */
export interface Detection {

    /**
     * @type {string}
     * @memberof Detection
     */
    id: string;

    /**
     * @type {string}
     * @memberof Detection
     */
    agrifieldId: string;

    /**
     * @type {number}
     * @memberof Detection
     */
    detectionTime: number;

    /**
     * @type {string}
     * @memberof Detection
     */
    type: string;

    /**
     * @type {Point}
     * @memberof Detection
     */
    position: Point;

    /**
     * @type {Array<string>}
     * @memberof Detection
     */
    photos: Array<string>;

    /**
     * @type {string}
     * @memberof Detection
     */
    note: string;

    /**
     * @type {any}
     * @memberof Detection
     */
    details: any;

    /**
     * @type {number}
     * @memberof Detection
     */
    creationTime: number;

    /**
     * @type {number}
     * @memberof Detection
     */
    lastUpdateTime: number;
}
