/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DetectionData } from './detection-data';
 /**
 * 
 *
 * @export
 * @interface Detection
 */
export interface Detection {

    /**
     * @type {string}
     * @memberof Detection
     */
    id: string;

    /**
     * @type {string}
     * @memberof Detection
     */
    agrifieldId: string;

    /**
     * @type {string}
     * @memberof Detection
     */
    sessionId?: string | null;

    /**
     * @type {number}
     * @memberof Detection
     */
    detectionTime: number;

    /**
     * @type {string}
     * @memberof Detection
     */
    detectionTypeId: string;

    /**
     * @type {DetectionData}
     * @memberof Detection
     */
    detectionData: DetectionData;

    /**
     * @type {number}
     * @memberof Detection
     */
    creationTime: number;

    /**
     * @type {number}
     * @memberof Detection
     */
    lastUpdateTime: number;
}
