/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DetectionDataPayload } from './detection-data-payload';
 /**
 * 
 *
 * @export
 * @interface DetectionMutationPayload
 */
export interface DetectionMutationPayload {

    /**
     * @type {number}
     * @memberof DetectionMutationPayload
     */
    detectionTime: number;

    /**
     * @type {string}
     * @memberof DetectionMutationPayload
     */
    detectionTypeId: string;

    /**
     * @type {DetectionDataPayload}
     * @memberof DetectionMutationPayload
     */
    detectionData: DetectionDataPayload;
}
