/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FileInfo } from './file-info';
import { ObservationPoint } from './observation-point';
import { ObservationTreatment } from './observation-treatment';
 /**
 * 
 *
 * @export
 * @interface DetectionDataPayload
 */
export interface DetectionDataPayload {

    /**
     * @type {string}
     * @memberof DetectionDataPayload
     */
    bbch: string;

    /**
     * @type {string}
     * @memberof DetectionDataPayload
     */
    notes: string;

    /**
     * @type {ObservationTreatment}
     * @memberof DetectionDataPayload
     */
    treatment: ObservationTreatment;

    /**
     * @type {Array<FileInfo>}
     * @memberof DetectionDataPayload
     */
    photos: Array<FileInfo>;

    /**
     * @type {Array<ObservationPoint>}
     * @memberof DetectionDataPayload
     */
    points: Array<ObservationPoint>;
}
