/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FileInfo } from './file-info';
import { Point } from './point';
 /**
 * 
 *
 * @export
 * @interface DetectionPhotoPayload
 */
export interface DetectionPhotoPayload {

    /**
     * @type {string}
     * @memberof DetectionPhotoPayload
     */
    caption: string;

    /**
     * @type {FileInfo}
     * @memberof DetectionPhotoPayload
     */
    photo: FileInfo;

    /**
     * @type {Point}
     * @memberof DetectionPhotoPayload
     */
    position?: Point;
}
