/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ObservationPoint } from './observation-point';
import { ObservationTreatment } from './observation-treatment';
 /**
 * 
 *
 * @export
 * @interface DetectionData
 */
export interface DetectionData {

    /**
     * @type {string}
     * @memberof DetectionData
     */
    bbch: string;

    /**
     * @type {string}
     * @memberof DetectionData
     */
    notes: string;

    /**
     * @type {ObservationTreatment}
     * @memberof DetectionData
     */
    treatment: ObservationTreatment;

    /**
     * @type {Array<string>}
     * @memberof DetectionData
     */
    photos: Array<string>;

    /**
     * @type {Array<ObservationPoint>}
     * @memberof DetectionData
     */
    points: Array<ObservationPoint>;
}
