/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DetectionTextUpdatePayload
 */
export interface DetectionTextUpdatePayload {

    /**
     * @type {string}
     * @memberof DetectionTextUpdatePayload
     */
    typology?: string | null;

    /**
     * @type {string}
     * @memberof DetectionTextUpdatePayload
     */
    method?: string | null;

    /**
     * @type {string}
     * @memberof DetectionTextUpdatePayload
     */
    locationAndScoreInstructions?: string | null;

    /**
     * @type {string}
     * @memberof DetectionTextUpdatePayload
     */
    bbchInstructions?: string | null;
}
