/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FileInfo } from './file-info';
import { Point } from './point';
 /**
 * 
 *
 * @export
 * @interface DetectionMutationPayload
 */
export interface DetectionMutationPayload {

    /**
     * @type {string}
     * @memberof DetectionMutationPayload
     */
    type: string;

    /**
     * @type {Point}
     * @memberof DetectionMutationPayload
     */
    position: Point;

    /**
     * @type {Array<FileInfo>}
     * @memberof DetectionMutationPayload
     */
    photos: Array<FileInfo>;

    /**
     * @type {string}
     * @memberof DetectionMutationPayload
     */
    note: string;

    /**
     * @type {any}
     * @memberof DetectionMutationPayload
     */
    details: any;
}
