/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface HarvestTypeUpdatePayload
 */
export interface HarvestTypeUpdatePayload {

    /**
     * @type {string}
     * @memberof HarvestTypeUpdatePayload
     */
    code?: string | null;

    /**
     * @type {string}
     * @memberof HarvestTypeUpdatePayload
     */
    label?: string | null;

    /**
     * @type {boolean}
     * @memberof HarvestTypeUpdatePayload
     */
    active?: boolean | null;

    /**
     * @type {number}
     * @memberof HarvestTypeUpdatePayload
     */
    sortOrder?: number | null;
}
