/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface HarvestType
 */
export interface HarvestType {

    /**
     * @type {string}
     * @memberof HarvestType
     */
    id: string;

    /**
     * @type {string}
     * @memberof HarvestType
     */
    code: string;

    /**
     * @type {string}
     * @memberof HarvestType
     */
    label: string;

    /**
     * @type {boolean}
     * @memberof HarvestType
     */
    active?: boolean;

    /**
     * @type {number}
     * @memberof HarvestType
     */
    sortOrder?: number;

    /**
     * @type {number}
     * @memberof HarvestType
     */
    creationTime: number;

    /**
     * @type {number}
     * @memberof HarvestType
     */
    lastUpdateTime: number;
}
