/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InvitationPublic } from './invitation-public';
 /**
 * Response for token validation
 *
 * @export
 * @interface InvitationValidateResponse
 */
export interface InvitationValidateResponse {

    /**
     * @type {boolean}
     * @memberof InvitationValidateResponse
     */
    valid: boolean;

    /**
     * @type {InvitationPublic}
     * @memberof InvitationValidateResponse
     */
    invitation?: InvitationPublic;

    /**
     * @type {string}
     * @memberof InvitationValidateResponse
     */
    error?: string | null;
}
