/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MultiDetectionEntryPayload } from './multi-detection-entry-payload';
import { ObservationTreatment } from './observation-treatment';
 /**
 * 
 *
 * @export
 * @interface MultiDetectionMutationPayload
 */
export interface MultiDetectionMutationPayload {

    /**
     * @type {number}
     * @memberof MultiDetectionMutationPayload
     */
    detectionTime: number;

    /**
     * @type {string}
     * @memberof MultiDetectionMutationPayload
     */
    bbch: string;

    /**
     * @type {ObservationTreatment}
     * @memberof MultiDetectionMutationPayload
     */
    treatment: ObservationTreatment;

    /**
     * @type {Array<MultiDetectionEntryPayload>}
     * @memberof MultiDetectionMutationPayload
     */
    entries: Array<MultiDetectionEntryPayload>;
}
