/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DetectionPhotoPayload } from './detection-photo-payload';
import { ObservationPoint } from './observation-point';
 /**
 * 
 *
 * @export
 * @interface MultiDetectionEntryPayload
 */
export interface MultiDetectionEntryPayload {

    /**
     * @type {string}
     * @memberof MultiDetectionEntryPayload
     */
    detectionTypeId: string;

    /**
     * @type {string}
     * @memberof MultiDetectionEntryPayload
     */
    notes: string;

    /**
     * @type {Array<DetectionPhotoPayload>}
     * @memberof MultiDetectionEntryPayload
     */
    photos: Array<DetectionPhotoPayload>;

    /**
     * @type {Array<ObservationPoint>}
     * @memberof MultiDetectionEntryPayload
     */
    points: Array<ObservationPoint>;

    /**
     * @type {boolean}
     * @memberof MultiDetectionEntryPayload
     */
    done?: boolean;
}
