/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ObservationType
 */
export interface ObservationType {

    /**
     * @type {string}
     * @memberof ObservationType
     */
    id: string;

    /**
     * @type {string}
     * @memberof ObservationType
     */
    typology: string;

    /**
     * @type {string}
     * @memberof ObservationType
     */
    method: string;

    /**
     * @type {string}
     * @memberof ObservationType
     */
    category: string;

    /**
     * @type {string}
     * @memberof ObservationType
     */
    locationAndScoreInstructions: string;

    /**
     * @type {string}
     * @memberof ObservationType
     */
    bchInstructions: string;

    /**
     * @type {string}
     * @memberof ObservationType
     */
    observationType: string;

    /**
     * @type {number}
     * @memberof ObservationType
     */
    rangeMin?: number | null;

    /**
     * @type {number}
     * @memberof ObservationType
     */
    rangeMax?: number | null;

    /**
     * @type {Array<string>}
     * @memberof ObservationType
     */
    counters?: Array<string>;

    /**
     * @type {number}
     * @memberof ObservationType
     */
    creationTime: number;
}
