/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ObservationCounter } from './observation-counter';
 /**
 * 
 *
 * @export
 * @interface ObservationData
 */
export interface ObservationData {

    /**
     * @type {number}
     * @memberof ObservationData
     */
    rangeValue?: number | null;

    /**
     * @type {Array<ObservationCounter>}
     * @memberof ObservationData
     */
    counters?: Array<ObservationCounter>;
}
