/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ObservationTypeUpdatePayload
 */
export interface ObservationTypeUpdatePayload {

    /**
     * @type {string}
     * @memberof ObservationTypeUpdatePayload
     */
    typology?: string | null;

    /**
     * @type {string}
     * @memberof ObservationTypeUpdatePayload
     */
    method?: string | null;

    /**
     * @type {string}
     * @memberof ObservationTypeUpdatePayload
     */
    category?: string | null;

    /**
     * @type {string}
     * @memberof ObservationTypeUpdatePayload
     */
    locationAndScoreInstructions?: string | null;

    /**
     * @type {string}
     * @memberof ObservationTypeUpdatePayload
     */
    observationHint?: string | null;

    /**
     * @type {string}
     * @memberof ObservationTypeUpdatePayload
     */
    observationType?: string | null;

    /**
     * @type {number}
     * @memberof ObservationTypeUpdatePayload
     */
    rangeMin?: number | null;

    /**
     * @type {number}
     * @memberof ObservationTypeUpdatePayload
     */
    rangeMax?: number | null;

    /**
     * @type {Array<string>}
     * @memberof ObservationTypeUpdatePayload
     */
    rangeLabels?: Array<string> | null;

    /**
     * @type {Array<string>}
     * @memberof ObservationTypeUpdatePayload
     */
    counters?: Array<string> | null;
}
