/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Contacts } from './contacts';
import { Office } from './office';
 /**
 * 
 *
 * @export
 * @interface OrganizationCreatePayload
 */
export interface OrganizationCreatePayload {

    /**
     * @type {string}
     * @memberof OrganizationCreatePayload
     */
    name: string;

    /**
     * @type {string}
     * @memberof OrganizationCreatePayload
     */
    piva: string;

    /**
     * @type {string}
     * @memberof OrganizationCreatePayload
     */
    rapresentative: string;

    /**
     * @type {string}
     * @memberof OrganizationCreatePayload
     */
    rapresentativeContact: string;

    /**
     * @type {string}
     * @memberof OrganizationCreatePayload
     */
    legalForm: string;

    /**
     * @type {Office}
     * @memberof OrganizationCreatePayload
     */
    office: Office;

    /**
     * @type {Contacts}
     * @memberof OrganizationCreatePayload
     */
    contacts: Contacts;
}
