/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 *
 *
 * @export
 * @interface OrganizationStatsAgrifield
 */
export interface OrganizationStatsAgrifield {
    id: string;
    name: string;
    harvest: string | null;
    creationTime: number | null;
    detectionCount: number;
}
