/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OrganizationStatsAgrifield } from './organization-stats-agrifield';
import { OrganizationStatsOrganization } from './organization-stats-organization';
import { OrganizationStatsWindow } from './organization-stats-window';

 /**
 *
 *
 * @export
 * @interface OrganizationStatsResponse
 */
export interface OrganizationStatsResponse {
    organization: OrganizationStatsOrganization;
    window: OrganizationStatsWindow;
    agrifieldCount: number;
    distinctHarvestCount: number;
    distinctHarvests: Array<string>;
    agrifields: Array<OrganizationStatsAgrifield>;
}
