/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Contacts } from './contacts';
import { FileInfo } from './file-info';
import { Office } from './office';
 /**
 * 
 *
 * @export
 * @interface OrganizationUpdatePayload
 */
export interface OrganizationUpdatePayload {

    /**
     * @type {string}
     * @memberof OrganizationUpdatePayload
     */
    rapresentative?: string | null;

    /**
     * @type {string}
     * @memberof OrganizationUpdatePayload
     */
    rapresentativeContact?: string | null;

    /**
     * @type {string}
     * @memberof OrganizationUpdatePayload
     */
    legalForm?: string | null;

    /**
     * @type {Office}
     * @memberof OrganizationUpdatePayload
     */
    office?: Office | null;

    /**
     * @type {FileInfo}
     * @memberof OrganizationUpdatePayload
     */
    logo?: FileInfo | null;

    /**
     * @type {FileInfo}
     * @memberof OrganizationUpdatePayload
     */
    cover?: FileInfo | null;

    /**
     * @type {Contacts}
     * @memberof OrganizationUpdatePayload
     */
    contacts?: Contacts | null;
}
