/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Contacts } from './contacts';
 /**
 * 
 *
 * @export
 * @interface Organization
 */
export interface Organization {

    /**
     * @type {string}
     * @memberof Organization
     */
    orgId: string;

    /**
     * @type {string}
     * @memberof Organization
     */
    name: string;

    /**
     * @type {string}
     * @memberof Organization
     */
    piva: string;

    /**
     * @type {string}
     * @memberof Organization
     */
    logo: string;

    /**
     * @type {string}
     * @memberof Organization
     */
    cover: string;

    /**
     * @type {Contacts}
     * @memberof Organization
     */
    contacts: Contacts;

    /**
     * @type {number}
     * @memberof Organization
     */
    creationTime: number;

    /**
     * @type {number}
     * @memberof Organization
     */
    lastUpdateTime: number;
}
