/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface StatusResponse
 */
export interface StatusResponse {

    /**
     * @type {number}
     * @memberof StatusResponse
     */
    status: number;

    /**
     * @type {string}
     * @memberof StatusResponse
     */
    message: string;
}
