/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AccountTypeEnum } from './account-type-enum';
import { OrganizationCreatePayload } from './organization-create-payload';
 /**
 * 
 *
 * @export
 * @interface UserCreatePayload
 */
export interface UserCreatePayload {

    /**
     * @type {string}
     * @memberof UserCreatePayload
     */
    firstName: string;

    /**
     * @type {string}
     * @memberof UserCreatePayload
     */
    lastName: string;

    /**
     * @type {string}
     * @memberof UserCreatePayload
     */
    email: string;

    /**
     * @type {AccountTypeEnum}
     * @memberof UserCreatePayload
     */
    accountType: AccountTypeEnum;

    /**
     * @type {string}
     * @memberof UserCreatePayload
     */
    phone: string;

    /**
     * @type {OrganizationCreatePayload}
     * @memberof UserCreatePayload
     */
    organization?: OrganizationCreatePayload | null;
}
