docker_image(
    name="docker",
    repository="darkform/tornatura.peronospora",
    image_tags=["latest", "1.0.3"],
    dependencies=[
        "src/python/peronospora:scheduler",
        "src/python/peronospora:api"
    ],
)
